//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesForWorkingWithCheques.ChequeWatcherWindowsService.ChequeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChequeServiceReference.IChequeService")]
    public interface IChequeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/SaveCheque", ReplyAction="http://tempuri.org/IChequeService/SaveChequeResponse")]
        void SaveCheque(ServicesForWorkingWithCheques.Domain.Core.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/SaveCheque", ReplyAction="http://tempuri.org/IChequeService/SaveChequeResponse")]
        System.Threading.Tasks.Task SaveChequeAsync(ServicesForWorkingWithCheques.Domain.Core.Cheque cheque);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetChequeList", ReplyAction="http://tempuri.org/IChequeService/GetChequeListResponse")]
        ServicesForWorkingWithCheques.Domain.Core.Cheque[] GetChequeList(int chequeCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChequeService/GetChequeList", ReplyAction="http://tempuri.org/IChequeService/GetChequeListResponse")]
        System.Threading.Tasks.Task<ServicesForWorkingWithCheques.Domain.Core.Cheque[]> GetChequeListAsync(int chequeCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChequeServiceChannel : ServicesForWorkingWithCheques.ChequeWatcherWindowsService.ChequeServiceReference.IChequeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChequeServiceClient : System.ServiceModel.ClientBase<ServicesForWorkingWithCheques.ChequeWatcherWindowsService.ChequeServiceReference.IChequeService>, ServicesForWorkingWithCheques.ChequeWatcherWindowsService.ChequeServiceReference.IChequeService {
        
        public ChequeServiceClient() {
        }
        
        public ChequeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChequeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SaveCheque(ServicesForWorkingWithCheques.Domain.Core.Cheque cheque) {
            base.Channel.SaveCheque(cheque);
        }
        
        public System.Threading.Tasks.Task SaveChequeAsync(ServicesForWorkingWithCheques.Domain.Core.Cheque cheque) {
            return base.Channel.SaveChequeAsync(cheque);
        }
        
        public ServicesForWorkingWithCheques.Domain.Core.Cheque[] GetChequeList(int chequeCount) {
            return base.Channel.GetChequeList(chequeCount);
        }
        
        public System.Threading.Tasks.Task<ServicesForWorkingWithCheques.Domain.Core.Cheque[]> GetChequeListAsync(int chequeCount) {
            return base.Channel.GetChequeListAsync(chequeCount);
        }
    }
}
